services:
  - type: web
    name: pou-pets-api
    env: node
    plan: free
    buildCommand: cd api-superheroes && npm install
    startCommand: cd api-superheroes && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000